name: Fetch vanilla_assets.zip and release

# 手动触发（你也可以改成定时触发）
on:
  workflow_dispatch:

jobs:
  fetch-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 允许写 Release

    steps:
      - name: Download vanilla_assets.zip
        run: |
          wget -q https://mc-assets-downloader.lonedev.workers.dev/itemsadder-required-vanilla-assets/vanilla_assets.zip -O vanilla_assets.zip
          ls -lh vanilla_assets.zip

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: vanilla-assets
          name: "Vanilla Assets (auto-sync)"
          body: |
            自动同步自：
            https://mc-assets-downloader.lonedev.workers.dev/itemsadder-required-vanilla-assets/vanilla_assets.zip
          files: vanilla_assets.zip
          token: ${{ secrets.GITHUB_TOKEN }}   # 默认自带
          # 如果想每次都覆盖同一条 release，使用：
          prerelease: false
          draft: false
